use_frameworks!

platform :ios, '10.0'

target 'MyFirstCocoaPodsLib_Example' do
  pod 'MyFirstCocoaPodsLib', :path => '../'

  target 'MyFirstCocoaPodsLib_Tests' do
    inherit! :search_paths

    
  end
end
